[tool.poetry]
name = "projectmix"
version = "0.1.0"
description = ""
authors = ["Chiara"]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.4.2"
hydra-core = "^1.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
