version: 2.1

orbs:
  python: circleci/python:3.10

jobs:
  build: 
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry

workflows:
  main: 
    jobs:
      - build
