version: 2.1


jobs:
  build: 
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry

workflows:
  main: 
    jobs:
      - build
