version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.0
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry

workflows:
  main: 
    jobs:
      - build-and-test
